// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: aid-service.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InteractionType int32

const (
	InteractionType_CALL        InteractionType = 0
	InteractionType_CHAT        InteractionType = 1
	InteractionType_DIALER_CALL InteractionType = 2
)

// Enum value maps for InteractionType.
var (
	InteractionType_name = map[int32]string{
		0: "CALL",
		1: "CHAT",
		2: "DIALER_CALL",
	}
	InteractionType_value = map[string]int32{
		"CALL":        0,
		"CHAT":        1,
		"DIALER_CALL": 2,
	}
)

func (x InteractionType) Enum() *InteractionType {
	p := new(InteractionType)
	*p = x
	return p
}

func (x InteractionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InteractionType) Descriptor() protoreflect.EnumDescriptor {
	return file_aid_service_proto_enumTypes[0].Descriptor()
}

func (InteractionType) Type() protoreflect.EnumType {
	return &file_aid_service_proto_enumTypes[0]
}

func (x InteractionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InteractionType.Descriptor instead.
func (InteractionType) EnumDescriptor() ([]byte, []int) {
	return file_aid_service_proto_rawDescGZIP(), []int{0}
}

type RegistrationState int32

const (
	// successful interaction queuing
	RegistrationState_SUCCESS RegistrationState = 0
	// interaction try to join to full queue
	RegistrationState_QUEUE_FULL RegistrationState = 1
	// interaction try to join queue where joinempty logic enabled
	RegistrationState_JOIN_EMPTY RegistrationState = 2
)

// Enum value maps for RegistrationState.
var (
	RegistrationState_name = map[int32]string{
		0: "SUCCESS",
		1: "QUEUE_FULL",
		2: "JOIN_EMPTY",
	}
	RegistrationState_value = map[string]int32{
		"SUCCESS":    0,
		"QUEUE_FULL": 1,
		"JOIN_EMPTY": 2,
	}
)

func (x RegistrationState) Enum() *RegistrationState {
	p := new(RegistrationState)
	*p = x
	return p
}

func (x RegistrationState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RegistrationState) Descriptor() protoreflect.EnumDescriptor {
	return file_aid_service_proto_enumTypes[1].Descriptor()
}

func (RegistrationState) Type() protoreflect.EnumType {
	return &file_aid_service_proto_enumTypes[1]
}

func (x RegistrationState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RegistrationState.Descriptor instead.
func (RegistrationState) EnumDescriptor() ([]byte, []int) {
	return file_aid_service_proto_rawDescGZIP(), []int{1}
}

type InteractionDistributionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// interaction which should be distributed to agent
	TargetInteraction *Interaction `protobuf:"bytes,1,opt,name=targetInteraction,proto3" json:"targetInteraction,omitempty"`
	// group ids ordered by prioritization (will be used by Powerdialer in future)
	Groups []int64 `protobuf:"varint,2,rep,packed,name=groups,proto3" json:"groups,omitempty"`
	// agent which have highest priority while distributing
	PreferredAgent string `protobuf:"bytes,3,opt,name=preferredAgent,proto3" json:"preferredAgent,omitempty"`
	// skill ids which required to handle interaction (in addition to queue skills)
	RequiredSkills []int64 `protobuf:"varint,4,rep,packed,name=requiredSkills,proto3" json:"requiredSkills,omitempty"`
	// Id of instance that sent request
	InstanceID string `protobuf:"bytes,5,opt,name=instanceId,proto3" json:"instanceId,omitempty"`
	// Time when interaction first enter to queue(used to return interaction to queue respecting previous position)
	PositionTimestamp int64 `protobuf:"varint,6,opt,name=positionTimestamp,proto3" json:"positionTimestamp,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *InteractionDistributionRequest) Reset() {
	*x = InteractionDistributionRequest{}
	mi := &file_aid_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InteractionDistributionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InteractionDistributionRequest) ProtoMessage() {}

func (x *InteractionDistributionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aid_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InteractionDistributionRequest.ProtoReflect.Descriptor instead.
func (*InteractionDistributionRequest) Descriptor() ([]byte, []int) {
	return file_aid_service_proto_rawDescGZIP(), []int{0}
}

func (x *InteractionDistributionRequest) GetTargetInteraction() *Interaction {
	if x != nil {
		return x.TargetInteraction
	}
	return nil
}

func (x *InteractionDistributionRequest) GetGroups() []int64 {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *InteractionDistributionRequest) GetPreferredAgent() string {
	if x != nil {
		return x.PreferredAgent
	}
	return ""
}

func (x *InteractionDistributionRequest) GetRequiredSkills() []int64 {
	if x != nil {
		return x.RequiredSkills
	}
	return nil
}

func (x *InteractionDistributionRequest) GetInstanceID() string {
	if x != nil {
		return x.InstanceID
	}
	return ""
}

func (x *InteractionDistributionRequest) GetPositionTimestamp() int64 {
	if x != nil {
		return x.PositionTimestamp
	}
	return 0
}

type Interaction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// unique id of interaction
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// type of interaction
	Type InteractionType `protobuf:"varint,2,opt,name=type,proto3,enum=com.globalbilgi.gbaidengine.grpc.InteractionType" json:"type,omitempty"`
	// queue name where interaction raised
	Queue string `protobuf:"bytes,3,opt,name=queue,proto3" json:"queue,omitempty"`
	// priority of interaction in it's queue (interactions with higher priority will be distributed first)
	Priority      int32 `protobuf:"varint,4,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Interaction) Reset() {
	*x = Interaction{}
	mi := &file_aid_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Interaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Interaction) ProtoMessage() {}

func (x *Interaction) ProtoReflect() protoreflect.Message {
	mi := &file_aid_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Interaction.ProtoReflect.Descriptor instead.
func (*Interaction) Descriptor() ([]byte, []int) {
	return file_aid_service_proto_rawDescGZIP(), []int{1}
}

func (x *Interaction) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Interaction) GetType() InteractionType {
	if x != nil {
		return x.Type
	}
	return InteractionType_CALL
}

func (x *Interaction) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *Interaction) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

type Queue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// queue name
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Queue) Reset() {
	*x = Queue{}
	mi := &file_aid_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Queue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Queue) ProtoMessage() {}

func (x *Queue) ProtoReflect() protoreflect.Message {
	mi := &file_aid_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Queue.ProtoReflect.Descriptor instead.
func (*Queue) Descriptor() ([]byte, []int) {
	return file_aid_service_proto_rawDescGZIP(), []int{2}
}

func (x *Queue) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type InteractionDistributionTimeEstimation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// show how many seconds remains to distribute interaction
	Estimation    int32 `protobuf:"varint,1,opt,name=estimation,proto3" json:"estimation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InteractionDistributionTimeEstimation) Reset() {
	*x = InteractionDistributionTimeEstimation{}
	mi := &file_aid_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InteractionDistributionTimeEstimation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InteractionDistributionTimeEstimation) ProtoMessage() {}

func (x *InteractionDistributionTimeEstimation) ProtoReflect() protoreflect.Message {
	mi := &file_aid_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InteractionDistributionTimeEstimation.ProtoReflect.Descriptor instead.
func (*InteractionDistributionTimeEstimation) Descriptor() ([]byte, []int) {
	return file_aid_service_proto_rawDescGZIP(), []int{3}
}

func (x *InteractionDistributionTimeEstimation) GetEstimation() int32 {
	if x != nil {
		return x.Estimation
	}
	return 0
}

type InteractionPosition struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// show position of interaction in it's queue (position numbering starts from 1)
	Position      int32 `protobuf:"varint,1,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InteractionPosition) Reset() {
	*x = InteractionPosition{}
	mi := &file_aid_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InteractionPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InteractionPosition) ProtoMessage() {}

func (x *InteractionPosition) ProtoReflect() protoreflect.Message {
	mi := &file_aid_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InteractionPosition.ProtoReflect.Descriptor instead.
func (*InteractionPosition) Descriptor() ([]byte, []int) {
	return file_aid_service_proto_rawDescGZIP(), []int{4}
}

func (x *InteractionPosition) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

type InteractionDistributionResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	State             RegistrationState      `protobuf:"varint,1,opt,name=state,proto3,enum=com.globalbilgi.gbaidengine.grpc.RegistrationState" json:"state,omitempty"`
	Estimation        int32                  `protobuf:"varint,2,opt,name=estimation,proto3" json:"estimation,omitempty"`
	Position          int32                  `protobuf:"varint,3,opt,name=position,proto3" json:"position,omitempty"`
	PositionTimestamp int64                  `protobuf:"varint,4,opt,name=positionTimestamp,proto3" json:"positionTimestamp,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *InteractionDistributionResponse) Reset() {
	*x = InteractionDistributionResponse{}
	mi := &file_aid_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InteractionDistributionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InteractionDistributionResponse) ProtoMessage() {}

func (x *InteractionDistributionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aid_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InteractionDistributionResponse.ProtoReflect.Descriptor instead.
func (*InteractionDistributionResponse) Descriptor() ([]byte, []int) {
	return file_aid_service_proto_rawDescGZIP(), []int{5}
}

func (x *InteractionDistributionResponse) GetState() RegistrationState {
	if x != nil {
		return x.State
	}
	return RegistrationState_SUCCESS
}

func (x *InteractionDistributionResponse) GetEstimation() int32 {
	if x != nil {
		return x.Estimation
	}
	return 0
}

func (x *InteractionDistributionResponse) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *InteractionDistributionResponse) GetPositionTimestamp() int64 {
	if x != nil {
		return x.PositionTimestamp
	}
	return 0
}

var File_aid_service_proto protoreflect.FileDescriptor

const file_aid_service_proto_rawDesc = "" +
	"\n" +
	"\x11aid-service.proto\x12 com.globalbilgi.gbaidengine.grpc\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb3\x02\n" +
	"\x1eInteractionDistributionRequest\x12[\n" +
	"\x11targetInteraction\x18\x01 \x01(\v2-.com.globalbilgi.gbaidengine.grpc.InteractionR\x11targetInteraction\x12\x16\n" +
	"\x06groups\x18\x02 \x03(\x03R\x06groups\x12&\n" +
	"\x0epreferredAgent\x18\x03 \x01(\tR\x0epreferredAgent\x12&\n" +
	"\x0erequiredSkills\x18\x04 \x03(\x03R\x0erequiredSkills\x12\x1e\n" +
	"\n" +
	"instanceId\x18\x05 \x01(\tR\n" +
	"instanceId\x12,\n" +
	"\x11positionTimestamp\x18\x06 \x01(\x03R\x11positionTimestamp\"\x96\x01\n" +
	"\vInteraction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12E\n" +
	"\x04type\x18\x02 \x01(\x0e21.com.globalbilgi.gbaidengine.grpc.InteractionTypeR\x04type\x12\x14\n" +
	"\x05queue\x18\x03 \x01(\tR\x05queue\x12\x1a\n" +
	"\bpriority\x18\x04 \x01(\x05R\bpriority\"\x1b\n" +
	"\x05Queue\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"G\n" +
	"%InteractionDistributionTimeEstimation\x12\x1e\n" +
	"\n" +
	"estimation\x18\x01 \x01(\x05R\n" +
	"estimation\"1\n" +
	"\x13InteractionPosition\x12\x1a\n" +
	"\bposition\x18\x01 \x01(\x05R\bposition\"\xd6\x01\n" +
	"\x1fInteractionDistributionResponse\x12I\n" +
	"\x05state\x18\x01 \x01(\x0e23.com.globalbilgi.gbaidengine.grpc.RegistrationStateR\x05state\x12\x1e\n" +
	"\n" +
	"estimation\x18\x02 \x01(\x05R\n" +
	"estimation\x12\x1a\n" +
	"\bposition\x18\x03 \x01(\x05R\bposition\x12,\n" +
	"\x11positionTimestamp\x18\x04 \x01(\x03R\x11positionTimestamp*6\n" +
	"\x0fInteractionType\x12\b\n" +
	"\x04CALL\x10\x00\x12\b\n" +
	"\x04CHAT\x10\x01\x12\x0f\n" +
	"\vDIALER_CALL\x10\x02*@\n" +
	"\x11RegistrationState\x12\v\n" +
	"\aSUCCESS\x10\x00\x12\x0e\n" +
	"\n" +
	"QUEUE_FULL\x10\x01\x12\x0e\n" +
	"\n" +
	"JOIN_EMPTY\x10\x022\xcb\x04\n" +
	"\n" +
	"AidService\x12\x9a\x01\n" +
	"\x13registerInteraction\x12@.com.globalbilgi.gbaidengine.grpc.InteractionDistributionRequest\x1aA.com.globalbilgi.gbaidengine.grpc.InteractionDistributionResponse\x12\x94\x01\n" +
	"\x1adistributionTimeEstimation\x12-.com.globalbilgi.gbaidengine.grpc.Interaction\x1aG.com.globalbilgi.gbaidengine.grpc.InteractionDistributionTimeEstimation\x12\x8b\x01\n" +
	"\x17queueWaitTimeEstimation\x12'.com.globalbilgi.gbaidengine.grpc.Queue\x1aG.com.globalbilgi.gbaidengine.grpc.InteractionDistributionTimeEstimation\x12{\n" +
	"\x13interactionPosition\x12-.com.globalbilgi.gbaidengine.grpc.Interaction\x1a5.com.globalbilgi.gbaidengine.grpc.InteractionPositionB\x15P\x01Z\x11aid-service/protob\x06proto3"

var (
	file_aid_service_proto_rawDescOnce sync.Once
	file_aid_service_proto_rawDescData []byte
)

func file_aid_service_proto_rawDescGZIP() []byte {
	file_aid_service_proto_rawDescOnce.Do(func() {
		file_aid_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aid_service_proto_rawDesc), len(file_aid_service_proto_rawDesc)))
	})
	return file_aid_service_proto_rawDescData
}

var file_aid_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_aid_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_aid_service_proto_goTypes = []any{
	(InteractionType)(0),                          // 0: com.globalbilgi.gbaidengine.grpc.InteractionType
	(RegistrationState)(0),                        // 1: com.globalbilgi.gbaidengine.grpc.RegistrationState
	(*InteractionDistributionRequest)(nil),        // 2: com.globalbilgi.gbaidengine.grpc.InteractionDistributionRequest
	(*Interaction)(nil),                           // 3: com.globalbilgi.gbaidengine.grpc.Interaction
	(*Queue)(nil),                                 // 4: com.globalbilgi.gbaidengine.grpc.Queue
	(*InteractionDistributionTimeEstimation)(nil), // 5: com.globalbilgi.gbaidengine.grpc.InteractionDistributionTimeEstimation
	(*InteractionPosition)(nil),                   // 6: com.globalbilgi.gbaidengine.grpc.InteractionPosition
	(*InteractionDistributionResponse)(nil),       // 7: com.globalbilgi.gbaidengine.grpc.InteractionDistributionResponse
}
var file_aid_service_proto_depIdxs = []int32{
	3, // 0: com.globalbilgi.gbaidengine.grpc.InteractionDistributionRequest.targetInteraction:type_name -> com.globalbilgi.gbaidengine.grpc.Interaction
	0, // 1: com.globalbilgi.gbaidengine.grpc.Interaction.type:type_name -> com.globalbilgi.gbaidengine.grpc.InteractionType
	1, // 2: com.globalbilgi.gbaidengine.grpc.InteractionDistributionResponse.state:type_name -> com.globalbilgi.gbaidengine.grpc.RegistrationState
	2, // 3: com.globalbilgi.gbaidengine.grpc.AidService.registerInteraction:input_type -> com.globalbilgi.gbaidengine.grpc.InteractionDistributionRequest
	3, // 4: com.globalbilgi.gbaidengine.grpc.AidService.distributionTimeEstimation:input_type -> com.globalbilgi.gbaidengine.grpc.Interaction
	4, // 5: com.globalbilgi.gbaidengine.grpc.AidService.queueWaitTimeEstimation:input_type -> com.globalbilgi.gbaidengine.grpc.Queue
	3, // 6: com.globalbilgi.gbaidengine.grpc.AidService.interactionPosition:input_type -> com.globalbilgi.gbaidengine.grpc.Interaction
	7, // 7: com.globalbilgi.gbaidengine.grpc.AidService.registerInteraction:output_type -> com.globalbilgi.gbaidengine.grpc.InteractionDistributionResponse
	5, // 8: com.globalbilgi.gbaidengine.grpc.AidService.distributionTimeEstimation:output_type -> com.globalbilgi.gbaidengine.grpc.InteractionDistributionTimeEstimation
	5, // 9: com.globalbilgi.gbaidengine.grpc.AidService.queueWaitTimeEstimation:output_type -> com.globalbilgi.gbaidengine.grpc.InteractionDistributionTimeEstimation
	6, // 10: com.globalbilgi.gbaidengine.grpc.AidService.interactionPosition:output_type -> com.globalbilgi.gbaidengine.grpc.InteractionPosition
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_aid_service_proto_init() }
func file_aid_service_proto_init() {
	if File_aid_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aid_service_proto_rawDesc), len(file_aid_service_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_aid_service_proto_goTypes,
		DependencyIndexes: file_aid_service_proto_depIdxs,
		EnumInfos:         file_aid_service_proto_enumTypes,
		MessageInfos:      file_aid_service_proto_msgTypes,
	}.Build()
	File_aid_service_proto = out.File
	file_aid_service_proto_goTypes = nil
	file_aid_service_proto_depIdxs = nil
}
