// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: aid-service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AidService_RegisterInteraction_FullMethodName        = "/com.globalbilgi.gbaidengine.grpc.AidService/registerInteraction"
	AidService_DistributionTimeEstimation_FullMethodName = "/com.globalbilgi.gbaidengine.grpc.AidService/distributionTimeEstimation"
	AidService_QueueWaitTimeEstimation_FullMethodName    = "/com.globalbilgi.gbaidengine.grpc.AidService/queueWaitTimeEstimation"
	AidService_InteractionPosition_FullMethodName        = "/com.globalbilgi.gbaidengine.grpc.AidService/interactionPosition"
)

// AidServiceClient is the client API for AidService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AidServiceClient interface {
	RegisterInteraction(ctx context.Context, in *InteractionDistributionRequest, opts ...grpc.CallOption) (*InteractionDistributionResponse, error)
	DistributionTimeEstimation(ctx context.Context, in *Interaction, opts ...grpc.CallOption) (*InteractionDistributionTimeEstimation, error)
	QueueWaitTimeEstimation(ctx context.Context, in *Queue, opts ...grpc.CallOption) (*InteractionDistributionTimeEstimation, error)
	InteractionPosition(ctx context.Context, in *Interaction, opts ...grpc.CallOption) (*InteractionPosition, error)
}

type aidServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAidServiceClient(cc grpc.ClientConnInterface) AidServiceClient {
	return &aidServiceClient{cc}
}

func (c *aidServiceClient) RegisterInteraction(ctx context.Context, in *InteractionDistributionRequest, opts ...grpc.CallOption) (*InteractionDistributionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InteractionDistributionResponse)
	err := c.cc.Invoke(ctx, AidService_RegisterInteraction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aidServiceClient) DistributionTimeEstimation(ctx context.Context, in *Interaction, opts ...grpc.CallOption) (*InteractionDistributionTimeEstimation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InteractionDistributionTimeEstimation)
	err := c.cc.Invoke(ctx, AidService_DistributionTimeEstimation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aidServiceClient) QueueWaitTimeEstimation(ctx context.Context, in *Queue, opts ...grpc.CallOption) (*InteractionDistributionTimeEstimation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InteractionDistributionTimeEstimation)
	err := c.cc.Invoke(ctx, AidService_QueueWaitTimeEstimation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aidServiceClient) InteractionPosition(ctx context.Context, in *Interaction, opts ...grpc.CallOption) (*InteractionPosition, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InteractionPosition)
	err := c.cc.Invoke(ctx, AidService_InteractionPosition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AidServiceServer is the server API for AidService service.
// All implementations must embed UnimplementedAidServiceServer
// for forward compatibility.
type AidServiceServer interface {
	RegisterInteraction(context.Context, *InteractionDistributionRequest) (*InteractionDistributionResponse, error)
	DistributionTimeEstimation(context.Context, *Interaction) (*InteractionDistributionTimeEstimation, error)
	QueueWaitTimeEstimation(context.Context, *Queue) (*InteractionDistributionTimeEstimation, error)
	InteractionPosition(context.Context, *Interaction) (*InteractionPosition, error)
	mustEmbedUnimplementedAidServiceServer()
}

// UnimplementedAidServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAidServiceServer struct{}

func (UnimplementedAidServiceServer) RegisterInteraction(context.Context, *InteractionDistributionRequest) (*InteractionDistributionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterInteraction not implemented")
}
func (UnimplementedAidServiceServer) DistributionTimeEstimation(context.Context, *Interaction) (*InteractionDistributionTimeEstimation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DistributionTimeEstimation not implemented")
}
func (UnimplementedAidServiceServer) QueueWaitTimeEstimation(context.Context, *Queue) (*InteractionDistributionTimeEstimation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueueWaitTimeEstimation not implemented")
}
func (UnimplementedAidServiceServer) InteractionPosition(context.Context, *Interaction) (*InteractionPosition, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InteractionPosition not implemented")
}
func (UnimplementedAidServiceServer) mustEmbedUnimplementedAidServiceServer() {}
func (UnimplementedAidServiceServer) testEmbeddedByValue()                    {}

// UnsafeAidServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AidServiceServer will
// result in compilation errors.
type UnsafeAidServiceServer interface {
	mustEmbedUnimplementedAidServiceServer()
}

func RegisterAidServiceServer(s grpc.ServiceRegistrar, srv AidServiceServer) {
	// If the following call pancis, it indicates UnimplementedAidServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AidService_ServiceDesc, srv)
}

func _AidService_RegisterInteraction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InteractionDistributionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AidServiceServer).RegisterInteraction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AidService_RegisterInteraction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AidServiceServer).RegisterInteraction(ctx, req.(*InteractionDistributionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AidService_DistributionTimeEstimation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Interaction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AidServiceServer).DistributionTimeEstimation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AidService_DistributionTimeEstimation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AidServiceServer).DistributionTimeEstimation(ctx, req.(*Interaction))
	}
	return interceptor(ctx, in, info, handler)
}

func _AidService_QueueWaitTimeEstimation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Queue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AidServiceServer).QueueWaitTimeEstimation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AidService_QueueWaitTimeEstimation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AidServiceServer).QueueWaitTimeEstimation(ctx, req.(*Queue))
	}
	return interceptor(ctx, in, info, handler)
}

func _AidService_InteractionPosition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Interaction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AidServiceServer).InteractionPosition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AidService_InteractionPosition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AidServiceServer).InteractionPosition(ctx, req.(*Interaction))
	}
	return interceptor(ctx, in, info, handler)
}

// AidService_ServiceDesc is the grpc.ServiceDesc for AidService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AidService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "com.globalbilgi.gbaidengine.grpc.AidService",
	HandlerType: (*AidServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "registerInteraction",
			Handler:    _AidService_RegisterInteraction_Handler,
		},
		{
			MethodName: "distributionTimeEstimation",
			Handler:    _AidService_DistributionTimeEstimation_Handler,
		},
		{
			MethodName: "queueWaitTimeEstimation",
			Handler:    _AidService_QueueWaitTimeEstimation_Handler,
		},
		{
			MethodName: "interactionPosition",
			Handler:    _AidService_InteractionPosition_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "aid-service.proto",
}
